version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    hostname: angular
    tty: true
    ports:
      - '4200:4200'
    volumes:
      - '.:/app'
      - './app/node_modules'
    networks:
      - app
networks:
  app:
