version: "3.7"

x-common-variables: &common-variables
  QUARKUS_PORT: 8080
  QUARKUS_PATH_API: /quarkus
  QUARKUS_SWAGGER_PATH: /swagger-ui
  QUARKUS_VALIDATOR_SWAGGER_URL: localhost:4200

services:
  maven:
    image: maven:3.6.3-jdk-11
    command: mvn clean install
    volumes:
      - ./backend:/usr/src/backend:rw
    working_dir: /usr/src/backend
  back:
    build:
      context: ./backend
      dockerfile: Dockerfile.jvm
    container_name: back
    hostname: quarkus
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"
    environment:
      <<: *common-variables
    networks:
      - app

  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: app
    hostname: angular
    tty: true
    ports:
      - "4200:4200"
    links:
      - back
    depends_on:
      - back
    volumes:
      - "./frontend:/app"
      - "./frontend/app/node_modules"
    networks:
      - app

networks:
  app:
