version: "3.4"

x-common-variables: &common-variables
  POSTGRES_DB: app
  POSTGRES_USER: app
  POSTGRES_PASSWORD: app

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.jvm
    container_name: indicador-mundial
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"
    environment:
      <<: *common-variables
    networks:
      - app

networks:
  app:
